// Generated by CoffeeScript 1.6.3
var MD5, excapeDot, filenameRegexp, fs, makeDate, matchName, moment, path;

moment = require('moment');

MD5 = require('MD5');

path = require('path');

fs = require('fs');

filenameRegexp = /^([\w\.]{3,10}\.)(\d{8}-[\w\d]{32}\.)?(\w{2,6})$/;

makeDate = function() {
  return moment().utc().format('MMDDHHmm');
};

matchName = function(name, md5text) {
  return name.indexOf(md5text) >= 0;
};

excapeDot = function(text) {
  return text.replace(/\./g, '\\.');
};

module.exports = function(grunt) {
  grunt.file.defaultEncoding = 'utf8';
  return grunt.registerMultiTask('deploy-with-md5', 'mine', function() {
    var _this = this;
    return this.files.map(function(item) {
      var md5List, oldFiles;
      oldFiles = fs.readdirSync(item.dest);
      md5List = [];
      item.src.map(function(relativeFile) {
        var appName, extName, match, md5, newName, newRegexp, oldBasename, pattern;
        grunt.log.writeln('now file:', relativeFile);
        md5 = MD5(grunt.file.read(relativeFile));
        md5List.push(md5);
        if (!(oldFiles.some(function(name) {
          return matchName(name, md5);
        }))) {
          grunt.log.writeln('handle item:', relativeFile);
          oldBasename = path.basename(relativeFile);
          match = oldBasename.match(filenameRegexp);
          appName = match[1];
          extName = match[3];
          pattern = "" + (excapeDot(appName)) + "(\\d{8}-[0-9a-f]{32})?\\." + extName;
          newRegexp = new RegExp(pattern);
          newName = "" + appName + (makeDate()) + "-" + md5 + "." + extName;
          grunt.file.copy(relativeFile, path.join(item.dest, newName));
          return _this.data.html.map(function(name) {
            var content;
            grunt.log.writeln('doing html:', name);
            content = grunt.file.read(name);
            content = content.replace(newRegexp, newName);
            return grunt.file.write(name, content);
          });
        }
      });
      return oldFiles.map(function(name) {
        if (!(md5List.some(function(md5) {
          return matchName(name, md5);
        }))) {
          grunt.log.writeln('deleting file:', name);
          return grunt.file["delete"](path.join(item.dest, name));
        }
      });
    });
  });
};
