// Generated by CoffeeScript 1.6.3
var MD5, excapeDot, filenameRegexp, fs, makeDate, matchName, moment, path;

moment = require('moment');

MD5 = require('MD5');

path = require('path');

fs = require('fs');

filenameRegexp = /^([\w\.]{3,10}\.)(\d{8}-[\w\d]{32}\.)?(\w{2,6})$/;

makeDate = function() {
  return moment().utc().format('MMDDHHmm');
};

matchName = function(name, md5text) {
  return name.indexOf(md5text) >= 0;
};

excapeDot = function(text) {
  return text.replace(/\./g, '\\.');
};

module.exports = function(grunt) {
  grunt.file.defaultEncoding = 'utf8';
  return grunt.registerMultiTask('deploy-with-md5', 'mine', function() {
    var _this = this;
    return this.files.map(function(item) {
      var oldFiles;
      oldFiles = fs.readdirSync(item.dest);
      return item.src.map(function(relativeFile) {
        var appName, expectName, extName, match, md5, newName, newRegexp, oldBasename, pattern;
        grunt.log.writeln('now file:', relativeFile);
        md5 = MD5(grunt.file.read(relativeFile));
        if (!(oldFiles.some(function(name) {
          return matchName(name, md5);
        }))) {
          grunt.log.writeln('handle item:', relativeFile);
          oldBasename = path.basename(relativeFile);
          match = oldBasename.match(filenameRegexp);
          appName = match[1];
          extName = match[3];
          pattern = "" + (excapeDot(appName)) + "(\\d{8}-[0-9a-f]{32})?\\." + extName;
          newRegexp = new RegExp(pattern);
          grunt.log.writeln('the newRegexp:', newRegexp);
          expectName = void 0;
          oldFiles.map(function(name) {
            grunt.log.writeln('the name %s, the expgex', name, pattern);
            if (name.match(newRegexp) != null) {
              return expectName = name;
            }
          });
          newName = "" + appName + (makeDate()) + "-" + md5 + "." + extName;
          grunt.file.copy(relativeFile, path.join(item.dest, newName));
          if (expectName != null) {
            grunt.file["delete"](path.join(item.dest, expectName));
          }
          grunt.log.writeln('the expectName:', expectName);
          return _this.data.html.map(function(name) {
            var content;
            grunt.log.writeln('doing html:', name);
            console.log(newRegexp);
            content = grunt.file.read(name);
            content = content.replace(newRegexp, newName);
            return grunt.file.write(name, content);
          });
        }
      });
    });
  });
};
